### ISSUE TITLE
Ask: How to put process name manually

### ISSUE THREAD

**Issue by raufalkautsar** [BryanGIG/PADumper#114]
how to put process name manual (idk process name is), idk why everytime i click select apps the apps always said not process found

**Comment by BryanGIG** [comment]
The process name usually a package name of the apk, you could try input it in

**Comment by raufalkautsar** [comment]
alr, its still not working

**Comment by Raufalkautsar** [comment]
im alr accept the permission

**Comment by Raufalkautsar** [comment]
==========================
Process : com.mobile.legends
[ERROR] java.lang.Exception: Process not found!
	at T1.a.b(SourceFile:421)
	at x.r.a(SourceFile:237)
	at x.r.c(SourceFile:14)
	at p.w.q(SourceFile:196)
	at u.T0.t(SourceFile:134)
	at J2.a.r(SourceFile:9)
	at s2.a.q1(SourceFile:79)
	at Y2.j.p(SourceFile:100)
	at Y2.j.F(SourceFile:33)
	at Y2.j.r(SourceFile:17)
	at p0.J.u0(SourceFile:51)
	at p0.J.b0(SourceFile:31)
	at t.f.b0(SourceFile:5)
	at t.D.b0(SourceFile:3)
	at p0.i.f(SourceFile:157)
	at p0.i.f(SourceFile:136)
	at p0.i.f(SourceFile:136)
	at p0.i.f(SourceFile:136)
	at p0.i.f(SourceFile:136)
	at p0.i.f(SourceFile:136)
	at p0.e.b(SourceFile:30)
	at p0.y.a(SourceFile:122)
	at v0.w.F(SourceFile:79)
	at v0.w.n(SourceFile:214)
	at v0.w.dispatchTouchEvent(SourceFile:76)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:451)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3375)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:413)
	at android.view.View.dispatchPointerEvent(View.java:12030)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4884)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4695)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4231)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4284)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4250)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4377)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4258)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4434)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4231)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4284)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4250)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4258)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4231)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6793)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6765)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6726)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6901)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:254)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:331)
	at android.os.Looper.loop(Looper.java:149)
	at android.app.ActivityThread.main(ActivityThread.java:6651)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

==========================

**Comment by raufalkautsar** [comment]
lol i am an idiot, i forgot to open in virtual space

**Comment by raufalkautsar** [comment]
nvm its working, my bad xd
