### ISSUE TITLE
Crash when click Select Apps

### ISSUE THREAD

**Issue by MlgmXyysd** [BryanGIG/PADumper#19]
Android Environment: Lenovo Xiaoxin Pad Pro 12.7 (Snapdragon) TB371FC / ZUI 15.0.291 / Android 13 Tiramisu / Tablet

```
10-15 23:22:27.992 18519 18519 E AndroidRuntime: FATAL EXCEPTION: main
10-15 23:22:27.992 18519 18519 E AndroidRuntime: Process: com.dumper.android, PID: 18519
10-15 23:22:27.992 18519 18519 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at java.lang.Class.isAssignableFrom(Class.java:589)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4853)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at android.os.Parcel.readParcelableInternal(Parcel.java:4766)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at android.os.Parcel.readValue(Parcel.java:4532)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at android.os.Parcel.readValue(Parcel.java:4312)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at android.os.Parcel.readListInternal(Parcel.java:5276)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at android.os.Parcel.readArrayListInternal(Parcel.java:5295)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at android.os.Parcel.readValue(Parcel.java:4562)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at android.os.Parcel.readValue(Parcel.java:4312)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at android.os.Parcel$LazyValue.apply(Parcel.java:4410)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at android.os.Parcel$LazyValue.apply(Parcel.java:4369)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at android.os.BaseBundle.getValue(BaseBundle.java:374)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at android.os.BaseBundle.getArrayList(BaseBundle.java:1486)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at android.os.Bundle.getParcelableArrayList(Bundle.java:1070)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at androidx.activity.h.j(SourceFile:5)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at u1.b.handleMessage(SourceFile:54)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8192)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
10-15 23:22:27.992 18519 18519 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
```

**Comment by BryanGIG** [comment]
Can you give steps to reproduce this issue?

**Comment by BryanGIG** [comment]
can you test if [this](https://github.com/BryanGIG/PADumper/suites/17531461943/artifacts/1001495533) solved the issue?
