### ISSUE TITLE
Apk forclose

### ISSUE THREAD

**Issue by QPLAYid** [BryanGIG/PADumper#7]
![Screenshot_2022-04-20-08-02-36-448_bin mt plus canary](https://user-images.githubusercontent.com/102419809/164115366-b92e0a10-5ab1-437f-a0d4-0327824f3d99.jpg)

Android 12
Poco X3 pro

**Comment by BryanGIG** [comment]
please provide logs

**Comment by QPLAYid** [comment]
> tolong berikan log

Di mana lognya

**Comment by QPLAYid** [comment]
> please provide logs

java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5264)
	at android.view.ViewGroup.addView(ViewGroup.java:5093)
	at android.view.ViewGroup.addView(ViewGroup.java:5030)
	at androidx.fragment.app.FragmentStateManager.addViewToContainer(FragmentStateManager.java:839)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:528)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
	at android.app.Activity.performStart(Activity.java:8270)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3780)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2282)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by QPLAYid** [comment]
Itu bro log nya

**Comment by QPLAYid** [comment]
Bro bro respon me

**Comment by QPLAYid** [comment]
Oke

**Comment by QPLAYid** [comment]
Selesai ? Bro ?

**Comment by QPLAYid** [comment]
Where new version app ?
